spring:
  datasource:
    username: ${db-username}
    password: ${db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db-url}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port:
    ${server-port}
grpc:
  server:
    address: ${GRPC_SERVER_ADDRESS}
